apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      initContainers:
      - name: init-hello
        image: python:3.11-slim
        command: ["python", "-c", "print('Hello World')"]
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80

